### PR TITLE
[Bugfix] Real time user location + small styling fixes

### LINKED ISSUE #27: [Bugfix] Fix issue with user location not updating
##  Description:
Fix the problem where user location is not updated.

## Objectives:
- User location is updated in real time

## Additional Information:
Collaborate with the team in case of any questions or problems.
Test the functionality thoroughly to ensure there are no bugs related to this issue.

### PR DESCRIPTION
**Pull request by PKrystian**
## Added:

- Added a fix to update user location in real time.
- Small styling fixes

### CODE REVIEW

File: app/src/main/java/com/example/fivenightsescape/MapsActivity.kt [hunk 1]
```diff
@@ -128,8 +133,7 @@ class MapsActivity : AppCompatActivity(), OnMapReadyCallback {
         }
     }
 
-    private fun gameInit(currentLatLng: LatLng)
-    {
+    private fun gameInit(currentLatLng: LatLng) {
```
Comment (MBigaj) [inline app/src/main/java/com/example/fivenightsescape/MapsActivity.kt:136]: instead style it how it was before for functions:

private fun functionName()
{
    // code
}

instead of 

private fun functionName() {
    // code
}

**Review by MBigaj — CHANGES_REQUESTED** [review]
Consider the style change but otherwise Well done

**Review by MBigaj — APPROVED** [review]
git git
